//! Gaussian Cube file reader for 3D PES scalar fields.
//! Parses .cube files generated by Fortran write_pes_cube.
//!
//! Line 2 carries a compact JSON metadata block describing the PES type
//! (pes_2d or pes_3d), scan plane, mobile atom, lattice, and symmetry info.

use serde::Deserialize;
use crate::crystal::Lattice;

/// Parsed from line 2 of the cube file. Carries PES-specific metadata.
#[derive(Debug, Clone, Deserialize)]
pub struct PesCubeMeta {
    #[serde(rename = "type")]
    pub data_type: Option<String>,           // "pes_2d" or "pes_3d"
    pub plane: Option<String>,               // 2D: "xy"/"xz"/"yz"
    pub scan_mode: Option<String>,           // "SP" or "RELAX"
    pub mobile_idx: Option<usize>,           // 0-based index of mobile atom
    pub mobile_el: Option<String>,           // element symbol
    pub fx_range: Option<[f64; 2]>,          // 2D fractional scan range
    pub fy_range: Option<[f64; 2]>,          // 2D fractional scan range
    pub fz_range: Option<[f64; 2]>,          // 3D fractional scan range on z
    pub lattice: Option<LatticeMeta>,        // explicit lattice params (override voxel recon)
    #[allow(dead_code)]  // 3D feature in active development
    pub use_symmetry: Option<bool>,          // 3D only
}

#[derive(Debug, Clone, Deserialize)]
pub struct LatticeMeta {
    pub a: f64,
    pub b: f64,
    pub c: f64,
    pub alpha: f64,
    pub beta: f64,
    pub gamma: f64,
}

#[derive(Debug, Clone)]
#[allow(dead_code)]  // origin/metadata/description carried for future display/debug
pub struct CubeData {
    pub nx: usize, pub ny: usize, pub nz: usize,
    pub origin: [f64; 3],
    pub voxel_vecs: [[f64; 3]; 3],
    pub atoms: Vec<CubeAtom>,
    pub field: Vec<f32>,
    pub metadata: String,       // line 2 raw JSON
    pub description: String,    // line 1
    pub pes_meta: Option<PesCubeMeta>,  // parsed line 2 (if valid PES JSON)
}

#[derive(Debug, Clone)]
pub struct CubeAtom {
    pub z: i32,
    pub x: f32, pub y: f32, pub z_coord: f32,
}

/// Parse a Gaussian Cube file. Returns CubeData with optional PES metadata.
pub fn parse_cube(path: &str) -> Result<CubeData, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let lines: Vec<&str> = content.lines().collect();
    if lines.len() < 6 {
        return Err("Cube file too short".into());
    }

    let description = lines[0].to_string();
    let metadata = lines[1].to_string();
    // Try to parse line 2 as PES metadata JSON (non-fatal on failure)
    let pes_meta: Option<PesCubeMeta> = serde_json::from_str(&metadata).ok();

    // Line 3: natom origin_x origin_y origin_z
    let parts: Vec<&str> = lines[2].split_whitespace().collect();
    let natom: usize = parts[0].parse()?;
    let origin = [parts[1].parse()?, parts[2].parse()?, parts[3].parse()?];

    // Lines 4-6: nx/ny/nz + voxel vectors
    let mut nx: usize = 0; let mut ny: usize = 0; let mut nz: usize = 0;
    let mut voxel_vecs = [[0.0f64; 3]; 3];
    for axis in 0..3 {
        let p: Vec<&str> = lines[3+axis].split_whitespace().collect();
        let n: usize = p[0].parse()?;
        match axis {
            0 => nx = n,
            1 => ny = n,
            _ => nz = n,
        }
        voxel_vecs[axis] = [p[1].parse()?, p[2].parse()?, p[3].parse()?];
    }

    // Atom lines
    let mut atoms = Vec::with_capacity(natom);
    for i in 0..natom {
        let p: Vec<&str> = lines[6+i].split_whitespace().collect();
        atoms.push(CubeAtom {
            z: p[0].parse()?,
            x: p[2].parse()?, y: p[3].parse()?, z_coord: p[4].parse()?,
        });
    }

    // Volumetric data (remaining lines, all floats)
    let n_data = nx * ny * nz;
    let data_start = 6 + natom;
    let mut field = Vec::with_capacity(n_data);
    for line in &lines[data_start..] {
        for val in line.split_whitespace() {
            let v: f32 = val.parse().unwrap_or(f32::NAN);
            field.push(v);
            if field.len() >= n_data { break; }
        }
        if field.len() >= n_data { break; }
    }
    if field.len() < n_data {
        field.resize(n_data, 0.0);
    }

    Ok(CubeData { nx, ny, nz, origin, voxel_vecs, atoms, field, metadata, description, pes_meta })
}

/// Detect if a file is a Gaussian Cube file.
pub fn is_cube(path: &str) -> bool {
    path.ends_with(".cube") || {
        std::fs::read_to_string(path)
            .map(|c| c.lines().count() >= 6
                && c.lines().nth(2).map(|l| l.split_whitespace().count() == 4).unwrap_or(false)
                && c.lines().nth(3).map(|l| l.split_whitespace().count() == 4).unwrap_or(false))
            .unwrap_or(false)
    }
}

#[allow(dead_code)]  // utility methods for volume render / PES features
impl CubeData {
    /// True if this cube file represents a 2D PES scan (nz == 1 with pes_2d metadata).
    pub fn is_pes_2d(&self) -> bool {
        self.nz == 1 && self.pes_meta.as_ref()
            .map(|m| m.data_type.as_deref() == Some("pes_2d") || m.plane.is_some())
            .unwrap_or(false)
    }

    /// True if this cube file represents a 3D PES scan.
    pub fn is_pes_3d(&self) -> bool {
        self.nz > 1 && self.pes_meta.as_ref()
            .map(|m| m.data_type.as_deref() == Some("pes_3d"))
            .unwrap_or(false)
    }

    /// (min, max) of valid (non-NaN) energy values.
    pub fn energy_range(&self) -> (f32, f32) {
        let mut e_min = f32::MAX;
        let mut e_max = f32::MIN;
        for &v in &self.field {
            if v.is_finite() {
                e_min = e_min.min(v);
                e_max = e_max.max(v);
            }
        }
        (e_min, e_max)
    }

    /// Extract lattice parameters.
    ///
    /// Normal case: voxel_vecs[i] * (n_i - 1) = lattice vector i.
    /// 2D PES (nz == 1): voxel_vecs[2] already is the full out-of-plane vector.
    /// If PES metadata provides explicit lattice params, use those instead.
    pub fn to_lattice(&self) -> Lattice {
        // Prefer explicit lattice from PES metadata (line 2 JSON)
        if let Some(ref meta) = self.pes_meta {
            if let Some(ref lm) = meta.lattice {
                return Lattice {
                    a: lm.a as f32, b: lm.b as f32, c: lm.c as f32,
                    alpha: lm.alpha as f32, beta: lm.beta as f32, gamma: lm.gamma as f32,
                };
            }
        }

        let nz_factor = if self.nz > 1 { (self.nz - 1) as f64 } else { 1.0_f64 };
        let a_vec = [self.voxel_vecs[0][0]*(self.nx-1) as f64,
                     self.voxel_vecs[0][1]*(self.nx-1) as f64,
                     self.voxel_vecs[0][2]*(self.nx-1) as f64];
        let b_vec = [self.voxel_vecs[1][0]*(self.ny-1) as f64,
                     self.voxel_vecs[1][1]*(self.ny-1) as f64,
                     self.voxel_vecs[1][2]*(self.ny-1) as f64];
        let c_vec = [self.voxel_vecs[2][0]*nz_factor,
                     self.voxel_vecs[2][1]*nz_factor,
                     self.voxel_vecs[2][2]*nz_factor];

        let a = (a_vec[0]*a_vec[0]+a_vec[1]*a_vec[1]+a_vec[2]*a_vec[2]).sqrt() as f32;
        let b = (b_vec[0]*b_vec[0]+b_vec[1]*b_vec[1]+b_vec[2]*b_vec[2]).sqrt() as f32;
        let c = (c_vec[0]*c_vec[0]+c_vec[1]*c_vec[1]+c_vec[2]*c_vec[2]).sqrt() as f32;

        let cos_al = (b_vec[0]*c_vec[0]+b_vec[1]*c_vec[1]+b_vec[2]*c_vec[2])/(b*c) as f64;
        let cos_be = (a_vec[0]*c_vec[0]+a_vec[1]*c_vec[1]+a_vec[2]*c_vec[2])/(a*c) as f64;
        let cos_ga = (a_vec[0]*b_vec[0]+a_vec[1]*b_vec[1]+a_vec[2]*b_vec[2])/(a*b) as f64;

        let alpha = cos_al.clamp(-1.0, 1.0).acos().to_degrees() as f32;
        let beta  = cos_be.clamp(-1.0, 1.0).acos().to_degrees() as f32;
        let gamma = cos_ga.clamp(-1.0, 1.0).acos().to_degrees() as f32;

        Lattice { a, b, c, alpha, beta, gamma }
    }

    /// Inverse lattice vectors (row-based, for Cartesian → fractional).
    pub fn inverse_vectors(&self) -> [[f32; 3]; 3] {
        let lattice = self.to_lattice();
        let inv = lattice.inverse_vectors();
        [
            [inv[0].x, inv[0].y, inv[0].z],
            [inv[1].x, inv[1].y, inv[1].z],
            [inv[2].x, inv[2].y, inv[2].z],
        ]
    }
}
