//! Gaussian Cube file reader for 3D PES scalar fields.
//! Parses .cube files generated by Fortran write_pes3d_cube.

use crate::crystal::Lattice;

#[derive(Debug, Clone)]
pub struct CubeData {
    pub nx: usize, pub ny: usize, pub nz: usize,
    pub origin: [f64; 3],
    pub voxel_vecs: [[f64; 3]; 3],
    pub atoms: Vec<CubeAtom>,
    pub field: Vec<f32>,
    pub metadata: String,  // line 2 of cube file
    pub description: String, // line 1
}

#[derive(Debug, Clone)]
pub struct CubeAtom {
    pub z: i32,
    pub x: f32, pub y: f32, pub z_coord: f32,
}

/// Parse a Gaussian Cube file. Returns Ok((CubeData, metadata_json_string)).
pub fn parse_cube(path: &str) -> Result<CubeData, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let lines: Vec<&str> = content.lines().collect();
    if lines.len() < 6 {
        return Err("Cube file too short".into());
    }

    let description = lines[0].to_string();
    let metadata = lines[1].to_string();
    // Line 3: natom origin_x origin_y origin_z
    let parts: Vec<&str> = lines[2].split_whitespace().collect();
    let natom: usize = parts[0].parse()?;
    let origin = [parts[1].parse()?, parts[2].parse()?, parts[3].parse()?];

    // Lines 4-6: nx/ny/nz + voxel vectors
    let mut nx: usize = 0; let mut ny: usize = 0; let mut nz: usize = 0;
    let mut voxel_vecs = [[0.0f64; 3]; 3];
    for axis in 0..3 {
        let p: Vec<&str> = lines[3+axis].split_whitespace().collect();
        let n: usize = p[0].parse()?;
        match axis {
            0 => nx = n,
            1 => ny = n,
            _ => nz = n,
        }
        voxel_vecs[axis] = [p[1].parse()?, p[2].parse()?, p[3].parse()?];
    }

    // Atom lines
    let mut atoms = Vec::with_capacity(natom);
    for i in 0..natom {
        let p: Vec<&str> = lines[6+i].split_whitespace().collect();
        atoms.push(CubeAtom {
            z: p[0].parse()?,
            x: p[2].parse()?, y: p[3].parse()?, z_coord: p[4].parse()?,
        });
    }

    // Volumetric data (remaining lines, all floats)
    let n_data = nx * ny * nz;
    let data_start = 6 + natom;
    let mut field = Vec::with_capacity(n_data);
    for line in &lines[data_start..] {
        for val in line.split_whitespace() {
            let v: f32 = val.parse().unwrap_or(0.0);
            field.push(v);
            if field.len() >= n_data { break; }
        }
        if field.len() >= n_data { break; }
    }
    if field.len() < n_data {
        field.resize(n_data, 0.0);
    }

    Ok(CubeData { nx, ny, nz, origin, voxel_vecs, atoms, field, metadata, description })
}

/// Detect if a file is a Gaussian Cube file (check for ".cube" extension or first-line pattern).
pub fn is_cube(path: &str) -> bool {
    path.ends_with(".cube") || {
        std::fs::read_to_string(path)
            .map(|c| c.lines().count() >= 6
                && c.lines().nth(2).map(|l| l.split_whitespace().count() == 4).unwrap_or(false)
                && c.lines().nth(3).map(|l| l.split_whitespace().count() == 4).unwrap_or(false))
            .unwrap_or(false)
    }
}

/// Extract lattice parameters from voxel vectors.
/// The voxel vectors are: vx = a/(nx-1), vy = b/(ny-1), vz = c/(nz-1).
/// So lattice vectors = voxel_vec * (n_i-1).
impl CubeData {
    pub fn to_lattice(&self) -> Lattice {
        let a_vec = [self.voxel_vecs[0][0]*(self.nx-1) as f64,
                     self.voxel_vecs[0][1]*(self.nx-1) as f64,
                     self.voxel_vecs[0][2]*(self.nx-1) as f64];
        let b_vec = [self.voxel_vecs[1][0]*(self.ny-1) as f64,
                     self.voxel_vecs[1][1]*(self.ny-1) as f64,
                     self.voxel_vecs[1][2]*(self.ny-1) as f64];
        let c_vec = [self.voxel_vecs[2][0]*(self.nz-1) as f64,
                     self.voxel_vecs[2][1]*(self.nz-1) as f64,
                     self.voxel_vecs[2][2]*(self.nz-1) as f64];

        let a = (a_vec[0]*a_vec[0]+a_vec[1]*a_vec[1]+a_vec[2]*a_vec[2]).sqrt() as f32;
        let b = (b_vec[0]*b_vec[0]+b_vec[1]*b_vec[1]+b_vec[2]*b_vec[2]).sqrt() as f32;
        let c = (c_vec[0]*c_vec[0]+c_vec[1]*c_vec[1]+c_vec[2]*c_vec[2]).sqrt() as f32;

        let cos_al = (b_vec[0]*c_vec[0]+b_vec[1]*c_vec[1]+b_vec[2]*c_vec[2])/(b*c) as f64;
        let cos_be = (a_vec[0]*c_vec[0]+a_vec[1]*c_vec[1]+a_vec[2]*c_vec[2])/(a*c) as f64;
        let cos_ga = (a_vec[0]*b_vec[0]+a_vec[1]*b_vec[1]+a_vec[2]*b_vec[2])/(a*b) as f64;

        let alpha = cos_al.clamp(-1.0, 1.0).acos().to_degrees() as f32;
        let beta  = cos_be.clamp(-1.0, 1.0).acos().to_degrees() as f32;
        let gamma = cos_ga.clamp(-1.0, 1.0).acos().to_degrees() as f32;

        Lattice { a, b, c, alpha, beta, gamma }
    }
}
